Added configuration option for setting mem_limit in /sys/block/zramX/…
systemd/zram-generator pull request #192
Opened 2024-02-17 16:54 UTC by Malgarion

…mem_limit, needed in cases when

zram device size is big with compression ratios that can't be fit in RAM yet zram device does not report as being full. Option is "zram-resident-limit = " and syntax is same as with setting 'zram-size ='. Tested on my system and works as expected, additional test may be needed.

2024-02-21 18:23 UTC, nabijaczleweli requested changes

2024-02-21 18:23 UTC, nabijaczleweli commented on man/zram-generator.conf.md
> +  Arithmetic operators (^%/\*-+), e, π, SI suffixes, log(), int(), ceil(), floor(), round(), abs(), min(), max(), and trigonometric functions are supported.
"Same format as `zram-size`.", merge with next para at the end

2024-02-21 18:23 UTC, nabijaczleweli commented on man/zram-generator.conf.md
> +  Defaults to *0* meaning there is no limit, usefull to set when having zram device bigger than available RAM.
"Defaults to *0* (no limit)."

2024-02-21 18:23 UTC, nabijaczleweli commented on src/config.rs
> +        Ok(())
this clearly duplicates the else in `set_disksize_if_enabled()`; lift it out

2024-02-21 18:23 UTC, nabijaczleweli commented on src/config.rs
> +            ));
clear copy-paste of the `"zram-size"` branch

2024-02-21 18:23 UTC, nabijaczleweli commented on zram-generator.conf.example
> +# The default is "0"
.

2024-02-21 18:23 UTC, nabijaczleweli commented on zram-generator.conf.example
> +# exceed 64MiB. Recomended value is ram / 2.
cite? by whom?

2024-02-21 18:23 UTC, nabijaczleweli commented on zram-generator.conf.example
> +# exceed 64MiB. Recomended value is ram / 2.
math wrong I think?

2024-02-21 18:23 UTC, nabijaczleweli commented on zram-generator.conf.example
> +# The maximum size of resident memory of zram device, as function of
"The maximum memory resident for this zram device, as a function of MemTotal, both in MB." Also format this like the sexion above :v

2024-02-24 19:13 UTC, Malgarion commented
Pushed new changes.

2024-02-25 15:16 UTC, merged